version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    restart: unless-stopped
    depends_on:
      - docmost-db
      - docmost-redis
    environment:
      APP_URL: 'https://docmost.ozeliurs.com'
      APP_SECRET: '${APP_SECRET}'
      DATABASE_URL: 'postgresql://docmost:W8oxymw3MdQuxbE6cETJhWmUXaTpRVJ6@docmost-db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      MAIL_DRIVER: "smtp"
      SMTP_HOST: "in-v3.mailjet.com"
      SMTP_PORT: "587"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_SECURE: "true"
      MAIL_FROM_ADDRESS: "docmost@ozeliurs.com"
      MAIL_FROM_NAME: "Docmost"
    volumes:
      - docmost:/app/data/storage
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docmost.rule=Host(`docmost.ozeliurs.com`)"
      - "traefik.http.routers.docmost.entrypoints=websecure"
      - "traefik.http.routers.docmost.tls.certresolver=letsencrypt"
      - "traefik.http.services.docmost.loadbalancer.server.port=3000"

  docmost-db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: docmost-db
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: W8oxymw3MdQuxbE6cETJhWmUXaTpRVJ6
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

  docmost-redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    container_name: docmost-redis
    volumes:
      - redis_data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

volumes:
  docmost:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/docmost/app'
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/docmost/db'
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/docmost/redis'
      o: bind

networks:
  traefik:
    external: true