services:
  docker-in-docker:
    image: docker:dind
    container_name: "docker_dind"
    privileged: "true"
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]
    restart: "unless-stopped"

  gitea:
    image: "code.forgejo.org/forgejo/runner:3.4.1"
    container_name: "forgejo-runner"
    command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'
    # command: '/bin/sh -c "sleep 5; forgejo-runner daemon"'
    restart: "unless-stopped"
    links:
      - docker-in-docker
    depends_on:
      docker-in-docker:
        condition: service_started
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    user: 1001:1001
    volumes:
      - /mnt/appdata/forgejo-runner:/data
