services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - readarr-appdata:/config
      - books:/books
    ports:
      - 8787:8787
    networks:
        - traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.readarr.rule=Host(`readarr.ozeliurs.com`)"
        - "traefik.http.routers.readarr.entrypoints=websecure"
        - "traefik.http.routers.readarr.tls.certresolver=letsencrypt"
        - "traefik.http.services.readarr.loadbalancer.server.port=8787"

networks:
    traefik:
        external: true

volumes:
    readarr-appdata:
      driver: local
      driver_opts:
        type: none
        device: '/mnt/appdata/readarr'
        o: bind
    books:
      external: true