services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.ozeliurs.com"
      SMTP_HOST: "in-v3.mailjet.com"
      SMTP_FROM: "vaultwarden@ozeliurs.com"
      SMTP_PORT: 587
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

    volumes:
      - vaultwarden-appdata:/data/
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.ozeliurs.com`)"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]


networks:
  traefik:
    external: true

volumes:
  vaultwarden-appdata:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/vaultwarden'
      o: bind