services:

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    restart: unless-stopped
    environment:
      APP_URL: "https://bookstack.ozeliurs.com"
      DB_HOST: "bookstack_db"
      DB_PORT: "3306"
      DB_USER: "bookstack"
      DB_DATABASE: "bookstackapp"
      DB_PASS: ${MYSQL_PASSWORD}
    volumes:
      - bookstack-appdata:/config
    depends_on:
      - bookstack_db
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.ozeliurs.com`)"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
      - "traefik.http.routers.bookstack.tls=true"
      - "traefik.http.routers.bookstack.tls.certresolver=letsencrypt"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "bookstackapp"
      MYSQL_USER: "bookstack"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - bookstack-dbdata:/config
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

networks:
  traefik:
    external: true

volumes:
  bookstack-appdata:
    driver: local
    driver_opts:
    type: none
    device: '/mnt/appdata/bookstack/app'
    o: bind
  bookstack-dbdata:
    driver: local
    driver_opts:
    type: none
    device: '/mnt/appdata/bookstack/db'
    o: bind