services:

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      paperless-redis:
        condition: service_healthy
    volumes:
      - paperless-appdata:/usr/src/paperless/data
      - paperless-media:/usr/src/paperless/media
    environment:
      PAPERLESS_URL: "https://paper.ozeliurs.com"
      PAPERLESS_REDIS: "redis://paperless-redis:6379"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`paper.ozeliurs.com`)"
      - "traefik.http.routers.paperless.entrypoints=websecure"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.routers.paperless.tls.certresolver=letsencrypt"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]

  paperless-redis:
    image: redis:6.0
    restart: unless-stopped
    container_name: paperless-redis
    networks:
      - traefik
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  traefik:
    external: true

volumes:
  paperless-appdata:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/paperless/app'
      o: bind
  paperless-media:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/paperless/media'
      o: bind