services:
  ozeliurs-com:
    image: ozeliurs/ozeliurs-com:latest
    container_name: ozeliurs-com
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ozeliurs.rule=Host(`ozeliurs.com`) || Host(`www.ozeliurs.com`)"
      - "traefik.http.routers.ozeliurs.entrypoints=websecure"
      - "traefik.http.routers.ozeliurs.tls=true"
      - "traefik.http.routers.ozeliurs.tls.certresolver=letsencrypt"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:5000" ]

networks:
  traefik:
    external: true