services:
  infisical-db-migration:
    container_name: infisical-db-migration
    depends_on:
      infisical-db:
        condition: service_healthy
    image: infisical/infisical:latest-postgres
    environment:
      DB_CONNECTION_URI: "postgresql://infisical:infisical@infisical-db:5432/infisical"
    command: npm run migration:latest
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      infisical-db:
        condition: service_healthy
      redis:
        condition: service_started
      infisical-db-migration:
        condition: service_completed_successfully
    image: infisical/infisical:latest-postgres
    environment:
      SITE_URL: "https://infisical.ozeliurs.com"
      DB_CONNECTION_URI: "postgresql://infisical:infisical@infisical-db:5432/infisical"
      REDIS_URL: "redis://redis:6379"

      ENCRYPTION_KEY: $ENCRYPTION_KEY
      AUTH_SECRET: $AUTH_SECRET

      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_FROM_ADDRESS: $SMTP_FROM_ADDRESS
      SMTP_FROM_NAME: $SMTP_FROM_NAME

      NODE_ENV: "production"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.infisical-backend.rule=Host(`infisical.ozeliurs.com`)"
      - "traefik.http.routers.infisical-backend.entrypoints=websecure"
      - "traefik.http.routers.infisical-backend.tls=true"
      - "traefik.http.routers.infisical-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.infisical-backend.loadbalancer.server.port=8080"

  redis:
    image: redis
    container_name: infisical-dev-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - traefik
    volumes:
      - redis_data:/data
    labels:
      - "traefik.enable=false"

  infisical-db:
    container_name: infisical-db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "infisical"
      POSTGRES_USER: "infisical"
      POSTGRES_DB: "infisical"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - traefik
    healthcheck:
      test: "pg_isready --username=infisical && psql --username=infisical --list"
      interval: 5s
      timeout: 10s
      retries: 10
    labels:
      - "traefik.enable=false"

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  traefik:
    external: true
