services:
  fusion:
    image: rook1e404/fusion:latest
    container_name: fusion
    restart: "unless-stopped"
    environment:
      PASSWORD: ${PASSWORD}
    volumes:
      - fusion-appdata:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fusion.rule=Host(`fusion.ozeliurs.com`)"
      - "traefik.http.routers.fusion.entrypoints=websecure"
      - "traefik.http.routers.fusion.tls=true"
      - "traefik.http.routers.fusion.tls.certresolver=letsencrypt"
      - "traefik.http.services.fusion.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true

volumes:
  fusion-appdata:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/fusion'
      o: bind