services:
  flomepage:
    image: ozeliurs/flomepage:latest
    restart: unless-stopped
    container_name: flomepage
    environment:
      IP2LOCATION_TOKEN: ${IP2LOCATION_TOKEN}
    volumes:
      - flomepage-appdata:/app/persistent
      - flomepage-ip2location:/app/IP2LOCATION
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flomepage.rule=Host(`flomepage.ozeliurs.com`)"
      - "traefik.http.routers.flomepage.entrypoints=websecure"
      - "traefik.http.routers.flomepage.tls=true"
      - "traefik.http.routers.flomepage.tls.certresolver=letsencrypt"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:5000" ]

networks:
  traefik:
    external: true

volumes:
  flomepage-appdata:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/flomepage/app'
      o: bind

  flomepage-ip2location:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/flomepage/ip2location'
      o: bind
