services:
  headscale:
    image: headscale/headscale:0.22.3
    container_name: headscale
    restart: unless-stopped
    entrypoint: headscale serve
    volumes:
      - headscale-appdata:/var/lib/headscale
      - ./config.yaml:/etc/headscale/config.yaml
      - ./acls.hujson:/etc/headscale/acls.hujson
    environment:
      HEADSCALE_OIDC_CLIENT_SECRET: ${HEADSCALE_OIDC_CLIENT_SECRET}
    ports:
      - "3478:3478"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`headscale.ozeliurs.com`)"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls=true"
      - "traefik.http.routers.headscale.tls.certresolver=letsencrypt"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "headscale", "users", "list"]
      interval: 30s
      timeout: 10s
      retries: 3

  discord-headscale-bot:
    image: ghcr.io/ozeliurs/headscale-discord-bot:latest
    container_name: discord-headscale-bot
    restart: unless-stopped
    environment:
      HEADSCALE_API_URL: ${HEADSCALE_API_URL}
      HEADSCALE_API_KEY: ${HEADSCALE_API_KEY}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}

networks:
  traefik:
    external: true

volumes:
  headscale-appdata:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/appdata/headscale"
      o: bind
