ffmpeg:
  camera:
    datacenter:
      name: Datacenter
      host: 82.65.214.187
      port: 554
      path: /stream1
      username: ${DATACENTER_USER}
      password: ${DATACENTER_PASSWORD}
      width: 1920
      height: 1080
      fps: 15
      codec: h264
      audio_codec: aac

mog2:
  motion_detector:
    cameras:
      datacenter:
        fps: 1
        trigger_recorder: true

nvr:
  datacenter:

webserver: