services:
  wakapi:
    image: ghcr.io/muety/wakapi
    restart: unless-stopped
    container_name: wakapi
    environment:
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_PASSWORD: "wakapi"
      WAKAPI_DB_HOST: "db"
      WAKAPI_DB_PORT: "5432"
      ENVIRONMENT: "prod"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wakapi.rule=Host(`wakapi.ozeliurs.com`)"
      - "traefik.http.routers.wakapi.entrypoints=websecure"
      - "traefik.http.routers.wakapi.tls=true"
      - "traefik.http.routers.wakapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.wakapi.loadbalancer.server.port=3000"

  db:
    image: postgres:12.3
    restart: unless-stopped
    container_name: wakapi-db
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_PASSWORD: "wakapi"
      POSTGRES_DB: "wakapi"
    volumes:
      - wakapi-db-data:/var/lib/postgresql/data
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

networks:
  traefik:
    external: true

volumes:
  wakapi-db-data:
    driver: local
    driver_opts:
      type: none
      device: '/mnt/appdata/wakapi'
      o: bind
