name: Check Service Collisions

on: [ push, pull_request ]

jobs:
  check-collisions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for service name collisions
        run: |
          services=$(find . -name 'docker-compose.yml' -exec docker compose -f {} up -d --dry-run \; 2>&1 | grep 'DRY-RUN MODE -  Container' | awk '{print $6}' | sort | uniq -d)
          echo "Found service name collisions: $services"
