name: Validate Docker Compose

on: [push, pull_request]

jobs:
  find-docker-compose-files:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.set-matrix.outputs.directories }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Find Docker Compose files
      id: set-matrix
      run: |
        dirs=$(find . -type f -name 'docker-compose.yml' -exec dirname {} \; | grep -v '/\.' | sort -u)
        echo "::set-output name=directories::$(echo $dirs | jq -R -s -c 'split("\n") | map(select(. != ""))')"

  validate:
    needs: find-docker-compose-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.find-docker-compose-files.outputs.directories) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate Docker Compose
      run: docker-compose -f ${{ matrix.directory }}/docker-compose.yml config