version: "3.9"
services:
  tgragnato:
    image: "ghcr.io/tgragnato/magnetico:latest"
    container_name: "magnetico"
    restart: unless-stopped
    command: "--database=sqlite3:///data/magnetico.sqlite3"
    volumes:
      - "magnetico-data:/data"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.magneticow.rule=Host(`magnetico.ozeliurs.com`)"
      - "traefik.http.routers.magneticow.entrypoints=websecure"
      - "traefik.http.routers.magneticow.tls.certresolver=letsencrypt"
      - "traefik.http.services.magneticow.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true

volumes:
  magnetico-data:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/appdata/magnetico"
      o: bind
